name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  ci_cd:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          # build: npm run build
          start: npm start
